# Generated by Django 5.2 on 2025-04-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0004_governmentscheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='agro_business_images/')),
                ('description', models.TextField()),
                ('cost_to_implement', models.CharField(max_length=200)),
                ('benefits', models.TextField()),
                ('profit', models.CharField(max_length=200)),
                ('loss', models.TextField(blank=True, null=True)),
                ('side_business', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
