# Generated by Django 5.2 on 2025-04-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0005_agrobusiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganicFarmingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='organic_farming/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
