# Generated by Django 5.2 on 2025-04-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0006_organicfarmingcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organicfarmingcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/agro_business_images/'),
        ),
    ]
