# Generated by Django 5.1.6 on 2025-04-22 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0007_alter_organicfarmingcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_first_time', models.BooleanField()),
                ('reason', models.TextField()),
                ('found_what_needed', models.BooleanField()),
                ('user_friendliness', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
